// Enum pour les villes marocaines
export const MoroccanCities = {
    Casablanca: 'Casablanca',
    Tanger: 'Tanger',
    Fes: 'Fès',
    Marrakech: 'Marrakech',
    Meknes: 'Meknès',
    Sale: 'Salé',
    Rabat: 'Rabat',
    Agadir: 'Agadir',
    Oujda: 'Oujda',
    Kenitra: 'Kénitra',
    Tetouan: 'Tétouan',
    Laayoune: 'Laayoune',
    Mohammedia: 'Mohammédia',
    ElJadida: 'El Jadida',
    Khouribga: 'Khouribga',
    BeniMellal: 'Béni Mellal',
    Khemisset: 'Khémisset',
    Nador: 'Nador',
    Taza: 'Taza',
    Berkane: 'Berkane',
    Safi: 'Safi',
};